/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	scbsecretv1 "github.com/harshajith/k8s-controller-secrets-crd/pkg/apis/scbsecret/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScbSecrets implements ScbSecretInterface
type FakeScbSecrets struct {
	Fake *FakeScbV1
	ns   string
}

var scbsecretsResource = schema.GroupVersionResource{Group: "scb.com", Version: "v1", Resource: "scbsecrets"}

var scbsecretsKind = schema.GroupVersionKind{Group: "scb.com", Version: "v1", Kind: "ScbSecret"}

// Get takes name of the scbSecret, and returns the corresponding scbSecret object, and an error if there is any.
func (c *FakeScbSecrets) Get(name string, options v1.GetOptions) (result *scbsecretv1.ScbSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scbsecretsResource, c.ns, name), &scbsecretv1.ScbSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*scbsecretv1.ScbSecret), err
}

// List takes label and field selectors, and returns the list of ScbSecrets that match those selectors.
func (c *FakeScbSecrets) List(opts v1.ListOptions) (result *scbsecretv1.ScbSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scbsecretsResource, scbsecretsKind, c.ns, opts), &scbsecretv1.ScbSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &scbsecretv1.ScbSecretList{ListMeta: obj.(*scbsecretv1.ScbSecretList).ListMeta}
	for _, item := range obj.(*scbsecretv1.ScbSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scbSecrets.
func (c *FakeScbSecrets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scbsecretsResource, c.ns, opts))

}

// Create takes the representation of a scbSecret and creates it.  Returns the server's representation of the scbSecret, and an error, if there is any.
func (c *FakeScbSecrets) Create(scbSecret *scbsecretv1.ScbSecret) (result *scbsecretv1.ScbSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scbsecretsResource, c.ns, scbSecret), &scbsecretv1.ScbSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*scbsecretv1.ScbSecret), err
}

// Update takes the representation of a scbSecret and updates it. Returns the server's representation of the scbSecret, and an error, if there is any.
func (c *FakeScbSecrets) Update(scbSecret *scbsecretv1.ScbSecret) (result *scbsecretv1.ScbSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scbsecretsResource, c.ns, scbSecret), &scbsecretv1.ScbSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*scbsecretv1.ScbSecret), err
}

// Delete takes name of the scbSecret and deletes it. Returns an error if one occurs.
func (c *FakeScbSecrets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scbsecretsResource, c.ns, name), &scbsecretv1.ScbSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScbSecrets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scbsecretsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &scbsecretv1.ScbSecretList{})
	return err
}

// Patch applies the patch and returns the patched scbSecret.
func (c *FakeScbSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *scbsecretv1.ScbSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scbsecretsResource, c.ns, name, pt, data, subresources...), &scbsecretv1.ScbSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*scbsecretv1.ScbSecret), err
}
