/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/harshajith/k8s-controller-secrets-crd/pkg/apis/gitsecret/v1"
	scheme "github.com/harshajith/k8s-controller-secrets-crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GitSecretsGetter has a method to return a GitSecretInterface.
// A group's client should implement this interface.
type GitSecretsGetter interface {
	GitSecrets(namespace string) GitSecretInterface
}

// GitSecretInterface has methods to work with GitSecret resources.
type GitSecretInterface interface {
	Create(*v1.GitSecret) (*v1.GitSecret, error)
	Update(*v1.GitSecret) (*v1.GitSecret, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.GitSecret, error)
	List(opts metav1.ListOptions) (*v1.GitSecretList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.GitSecret, err error)
	GitSecretExpansion
}

// gitSecrets implements GitSecretInterface
type gitSecrets struct {
	client rest.Interface
	ns     string
}

// newGitSecrets returns a GitSecrets
func newGitSecrets(c *GitsecretV1Client, namespace string) *gitSecrets {
	return &gitSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitSecret, and returns the corresponding gitSecret object, and an error if there is any.
func (c *gitSecrets) Get(name string, options metav1.GetOptions) (result *v1.GitSecret, err error) {
	result = &v1.GitSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitsecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitSecrets that match those selectors.
func (c *gitSecrets) List(opts metav1.ListOptions) (result *v1.GitSecretList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GitSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitSecrets.
func (c *gitSecrets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gitsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a gitSecret and creates it.  Returns the server's representation of the gitSecret, and an error, if there is any.
func (c *gitSecrets) Create(gitSecret *v1.GitSecret) (result *v1.GitSecret, err error) {
	result = &v1.GitSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gitsecrets").
		Body(gitSecret).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gitSecret and updates it. Returns the server's representation of the gitSecret, and an error, if there is any.
func (c *gitSecrets) Update(gitSecret *v1.GitSecret) (result *v1.GitSecret, err error) {
	result = &v1.GitSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gitsecrets").
		Name(gitSecret.Name).
		Body(gitSecret).
		Do().
		Into(result)
	return
}

// Delete takes name of the gitSecret and deletes it. Returns an error if one occurs.
func (c *gitSecrets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitsecrets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitSecrets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitsecrets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gitSecret.
func (c *gitSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.GitSecret, err error) {
	result = &v1.GitSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gitsecrets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
